version: '3'
services:
  ## Once kafka is started, run an exec command with:
  ## > cd /etc/kafka/jaas
  ## > kafka-acls --bootstrap-server localhost:9092 --command-config admin-client.properties --add --operation All --allow-principal User:admin --topic "*"
  ## > kafka-acls --bootstrap-server localhost:9092 --command-config admin-client.properties --list
  kafka:
    ## Resource:
    ## - https://github.com/apache/kafka/blob/trunk/docker/examples/README.md
    ## - https://rafael-natali.medium.com/running-kafka-in-kubernetes-with-kraft-mode-and-sasl-authentication-f7350eaba81f
    ## - https://github.com/vdesabou/kafka-docker-playground/tree/master/environment/sasl-scram
    image: apache/kafka:3.8.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - "C:\\Projects\\seed-kafka\\infra\\secrets:/etc/kafka/jaas/"
    environment:
    # KRaft settings
      KAFKA_NODE_ID: 1
      CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
    # Listeners
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
      KAFKA_LISTENERS: CONTROLLER://kafka:29093,INTERNAL://kafka:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
    # SASL
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SASL_ENABLED_MECHANISMS: 'PLAIN,SCRAM-SHA-512'
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: 'PLAIN'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
      KAFKA_SASL_MECHANISM_EXTERNAL_PROTOCOL: 'PLAIN'
      KAFKA_SECURITY_PROTOCOL: 'SASL_PLAINTEXT'
    # JAAS config: https://kafka.apache.org/documentation/#brokerconfigs_sasl.jaas.config
      #KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: 'SCRAM-SHA-512'
      #KAFKA_LISTENER_NAME_CONTROLLER_SCRAM-SHA-512_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
      #KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: 'SCRAM-SHA-512'
      #KAFKA_LISTENER_NAME_INTERNAL_SCRAM-SHA-512_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
      #KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: 'SCRAM-SHA-512'
      #KAFKA_LISTENER_NAME_EXTERNAL_SCRAM-SHA-512_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin-secret";'
      # ACL
      KAFKA_SUPER_USERS: 'User:admin;User:ANONYMOUS'
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'false'
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/jaas/kafka_server_jaas.conf"
      KAFKA_EARLY_START_LISTENERS: CONTROLLER
    # Settings
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_NODE_ID: 1
  #     KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
  #     KAFKA_LISTENERS: 'INTERNAL://kafka:29092,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9092'
  #     KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
  #     KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
  #     KAFKA_PROCESS_ROLES: 'broker,controller'
  #     KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #     CLUSTER_ID: 'ciWo7IWazngRchmPES6q5A=='
  #   restart: always

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    restart: always
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_PLAINTEXT
      SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
      SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";'
      SCHEMA_REGISTRY_DEBUG: 'true'
  
  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:29092"
                security.protocol: SASL_PLAINTEXT
                sasl.mechanism: PLAIN
                sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";'
              schema-registry:
                url: "http://schema-registry:8081"
    ports:
      - 9082:8080
  
  klaw-core:
    image: aivenoy/klaw-core:latest
    container_name: klaw-core
    restart: always
    environment:
      KLAW_CLUSTERAPI_ACCESS_BASE64_SECRET: VGhpc0lzRXhhY3RseUEzMkNoYXJTdHJpbmdTZWNyZXQK
      SPRING_DATASOURCE_URL: "jdbc:h2:file:/klaw/klawprodb;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE;"
      KLAW_CLUSTERAPI_URL: "http://klaw-cluster-api:9343"
    volumes:
      - "klaw_data:/klaw"
    extra_hosts:
      - "moby:127.0.0.1"
    ports:
      - 9097:9097

  klaw-cluster-api:
    image: aivenoy/klaw-cluster-api:latest
    hostname: klaw-cluster-api
    container_name: klaw-cluster-api
    restart: unless-stopped
    environment:
      KLAW_CLUSTERAPI_ACCESS_BASE64_SECRET: VGhpc0lzRXhhY3RseUEzMkNoYXJTdHJpbmdTZWNyZXQK
      DEV1_KAFKASASL_JAASCONFIG_PLAIN: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";'
    volumes:
      - "klaw_data:/klaw"
    extra_hosts:
      - "moby:127.0.0.1"
    ports:
      - 9343:9343

volumes:
  klaw_data:
    driver: local

networks:
  default:
    external: true
    name: klaw